module_purge.lua
utils.lua

This module save last activity of each user and let administrators purge roles of inactive users.
Activity saved:
- Server join
- Messages
- Reaction adding
- Reaction removing
Commands added:
- **!dryPurgeRoles <duration>** : count inactives users
- **!purgeRoles <duration>** : remove roles of inactives users
Note: all users not stored in "purge" files will be considered as active to prevent removing roles on actives users

Inactive users: roles "purge" module

---

module_poll.lua

We can now remove poll reactions or add some other reactions without problem.
If we remove a poll reaction, the bot will tell us in the results report by adding a " (deleted)" at the end of the field name.
If we add a reaction other than the poll ones, the bot will just don't care at all.

Poll: Improve reactions handling system

---

module_poll.lua

Polls' results are now optionally displayable as progress bars. The option, `UseProgressBars`, is enabled by default.
Here's a preview:
Additionally, some messages have been updated (they are now less exclamative).

[Polls] Added an option to display results as progress bars

---

module_poll.lua

Fix some divisions by zero when it has no vote at all.
ProgressBars were not filled with spaces and percentages were not 0 but some giant random numbers.

Poll: Fix and refactor ProgressBars feature

---

bot_modules.lua

There was an issue when setting a module's configuration item to have a default value of `false` but not specifying that it should be optional. 
The `not` operator was coercing the received `false` value instead of checking if the value was `nil` in order to reject the module because of bad configuration. 
This PR fixes this by correctly checking the content of the `Default` parameter of a configuration option of a module. 
Additionally, this PR adds the module name in the error message when an error occurs.

Fix optional parameters in a module's configuration options

---

bot_modules.lua
module_quote.lua

This PR, which is dependent on #17, adds two new configuration options. 
The new `DeleteInvokationOnAutoQuote` setting allows to automatically delete the message that triggers a quote when auto-quoting. This setting defaults to `false`. 
The new `DeleteInvokationOnManualQuote` setting allows to automatically delete the message when using the `!quote` command. This setting defaults to `false`. 
Additionally, a new optional parameter for the `!quote` command has been added. This boolean parameter determines if the command should be deleted. 
For instance, `!quote 674011949842825235 true` will quote a message and then delete the command. 
Also, if `DeleteInvokationOnManualQuote` is set to true, but `false` is passed as the second parameter of `!quote`, the command will not be deleted (eg. …

Allow deletion of the command or message that triggers a quote

---

module_welcome.lua

`{userTag}` is replaced by the user name in the following format: `Foo#0000`.
`{userMention}` is replaced by the user mention string.
The usage of `{user}` in default messages has been replaced by either `{userTag}` or `{userMention}`.
This allows message description to present both of them, having the same behavior regardless of the message type.
**Note**
Support for the old `{user}` parameter is kept in order to avoid to break old configurations.

Welcome: Add {userTag} and {userMention}

---

bot_commands.lua

Adds a BotAware parameter when registering function, defaulted to false, which specify if a bot can call a specific command.
Maybe it will be useless, but I don't want to remove such an ability.
**Example of a minimal hello world module, triggerable by a bot**
```
Module.Name = "helloworld"
function Module:OnLoaded()
Bot:RegisterCommand({
Name = "helloworld",
Args = {},
BotAware = true,
Help = "Just an example of bot aware command",
Func = function (message)
message:reply("Hello world!")
end
})
return true
end
```
**This is critical because it applies to nearly all commands. As long as the bot has the administrator permission, it can call every command, except those reserved to the instance owner.**
For example, Carlbot has an `echo` command, and with that, it is possible to activate the …

[CRITICAL] Fixes bots being able to call commands

---

module_warn.lua

Hey, here is a little warn module that holds all the warns, reasons and authors for each users
Three new commands:
- warn <target> [reason]
- warnlist <target>
- clearwarns <target>
After a specified amount of warn the user gets muted, here is the formula:
warns % given_amount == 0 -> muted for a default duration of 1 hour (in the configuration)
The duration then increases like this: default_duration * (warns / given_amount)
There are ban messages in a specified channel when the user gets enough warns too. I decided to leave the choice to ban the member to the moderation team.

Warn Module

---

module_sentry.lua

Add a *sentry* module: the bot sends an "alert" in the specified channel if a "monitored" user joins the server or if a "monitored" user sends a message in the server, if keywords are specified the bot will alert only if the message contains one of the specified keywords (case insensitive).
There are some bad nomenclatures where I couldn't find better.
About `{message}` I preferred to put only the link of the message, even if the bot does not quote the message unfortunately.
```js
{
"SentryChannel": "769564333112819729",
"MonitoredJoins": ["235088799074484224"],
"MonitoredMessages": {
"294325577945448449": ["aria"],
"83928726282174464": ["JS"],
"282201728097583104": [] // empty array for no keywords (match any message)
},
"JoinAlert": "The monitored user {userTag} ({userId}) has joined …
```

add sentry module

---

module_logs.lua

This is spamming logs when people join servers.

Prevent spamming username change on join

---

module_userinfo.lua

I have removed the presence status because it is not essential information and requires a privileged intent.

Do not show presence when no guildPresences intent

---

deps/discordia/libs/client/API.lua
deps/discordia/libs/containers/Guild.lua
deps/discordia/libs/endpoints.lua
deps/discordia/libs/enums.lua
module_twitch.lua

This PR adds API to use Scheduled events and create them if needed when a Twitch stream begins.
Changelog:
- Add API endpoints/enums for scheduled events
- Expose those endpoints to the bot
- Create an event if ShouldCreateDiscordEvent is checked in TwitchConfig
- Event duration is CreateDiscordEventDuration or 3600 by default
Events examples:
Tested with a custom command as I can't test real twitch notifications.
The custom command:
```
self:RegisterCommand({
Name = "testa",
Silent = false,
Args = {
},
Help = "Test things",
Func = function(commandMessage, channel)
commandMessage:reply("ok")
commandMessage.guild:createScheduledEvents(
enums.scheduledEventsEntityTypes.external,
string.format("https://twitch.tv/%s", "elanis42"),
"Test title",
enums.scheduledEventsPrivacyLevel.guild_only, …
```

Add ability to create a Scheduled event with Not A Bot twitch stream detection

---

bot_utility.lua
localization/en.lua
localization/fr.lua
module_prune.lua

I have also renamed a parameter in Bot:DecodeMessage to avoid confusion, this parameter is not a message object and a local variable with the same name already exists inside the function.

use the Bot.ConfigType.Message type in module prune

---

bot_utility.lua
module_warn.lua

- fix: the warn module crashes when the `warnlist` command is used on a member who has been warned by a moderator who has left the guild
- update: the structure of the file `persistentData` has changed, making add and deletion of user entries easier
- add: a temporary function `ConvertDataFormat` has been added to convert persistentData format to the new format
- fix: when the `clearwarns` command is used, the warnings are removed from the file but the user's entry is not deleted, so the `persistentData` file grows indefinitely

Fix some bugs in module warn

---

bot_commands.lua
module_quote.lua

stop triggering the autoquote when using !prunefrom or other commands that take a message link as parameter

do not trigger autoquote module when writting a command message

---

localization/en.lua
localization/fr.lua
module_pin.lua

These new commands allow the owner of a thread to pin and unpin messages in his thread. The members with permission "manageMessages" can also use them.
cf: https://github.com/NotANameServer/discord/issues/51

add: commands pin and unpin

---

module_logs.lua

```lua
if data.nicknames[member.id] ~= nil and data.nicknames[member.id] ~= member.nickname then
logChannel:send({
embed = {
title = "Nickname changed",
description = string.format("%s - `%s` → `%s`", member.mentionString, data.nicknames[member.id], member.name),
timestamp = discordia.Date():toISO('T', 'Z')
}
})
end
-- [...]
data.nicknames[member.id] = member.name
```
This condition is comparing the nickname instead of name, which makes the bot logging a nickname change every time a member updates itself.

Fix nickname logging spam

---

module_userinfo.lua

some pseudo with multiple underscores like "`_mySuperName_`" are displayed in italic

fix: fullnames and nicknames containing underscores are incorrectly displayed

---

bot_commands.lua
deps/discordia/libs/containers/Message.lua
localization/en.lua
localization/fr.lua

The "help" command cannot actually display all commands in an embed because there are too many. This PR fixes this issue by paging the embed.

Fix the embed of the help command for admins
