- module_purge.lua
This pull request adds following functionalities:
- Register all unknown members on launch ( #5 )
- New command to kick instead of removing roles ( #4   )
> Purge module update

- config.lua.default
- module_poll.lua
You don't have to configure the module for it to work : people with the administrator permission can already create polls, specify channel, etc.
**It has 3 types of parameters:**
- **Permission**: One or more roles allowed or disallowed to do something. 
Please note that **members with the administrator permission are bypassing these rules**.
- **Default**: This can be overriden when initializing a poll.
- **Behavior**: This cannot be overriden and is affecting all the polls.
---
Most of the informations are already on the screenshot. This is just like a minimal wiki-like thing.
- #### AllowedRoles
**Description:** Roles allowed to create polls
**Type:** Permission
- #### SpecifyChannelAllowedRoles
**Description:** Roles allowed to specify where to send a poll
**Type:** Permission
- #### …
> Create poll module

- module_poll.lua
Commands renamed previously:
- initpoll -> createpoll
- deinitpoll -> cancelpoll
> Poll: Update some literals following commands rename

- module_modo.lua
- module_poll.lua
I fixed the bug where we couldn't report a message when there is an image. Now it's showing "no content" in the "Message content" section.
> [bug] Modo: report a message when there is an image

- module_poll.lua
This is the implementation of this idea from my Not a Bot ideas kanban.
This adds a new optional parameter `MostVotedRelative`
And it looks like this :
Btw, it has been tested and it is ready to be merged
> Poll: Add an optional parameter to make progressbars relative to the most voted choice

- deps/discordia/libs/containers/Message.lua
- module_quote.lua
Normally it works, but it's better to test it anyway.
> sticker quote module support

- config.lua.default
- module_userinfo.lua
> Add module userinfo

- module_nickname.lua
Fixing a small debug typo I kept in the module code
Max row amount: 5, including header/pagination, we can have page size of 3
> nickname: Pagesize should be 3 not 2

- module_raid.lua
Hello,
I updated the spam words/hint list based on recent spams we got on Not a Name server. I also added 2 discord domain names to URL whitelist.
Please tell me if I need to move some words from a category to another.
Feel free to review and comment.
> Update antispam to follow new bot trends

- module_modo.lua
> #63 - Check moderator permissions when interacting with alert

- module_logs.lua
- module_raid.lua
Fills #49 & #41
- Channel creation/deletion log:
- Username change log:
- Antispam message log:
> Logs improvement

- module_userinfo.lua
The current list is displayed in a markdown block, which results in nicknames containing special markdown characters (such as underscore) not being displayed correctly. I have replaced the markdown bloc by a text bloc.
I have also used tabs instead of spaces to remain consistent with the way the code in the other modules has been indented.
> Fix render problems in the users list

- module_raid.lua
> Add more spam words / hints based on #72

- module_raid.lua
- utils.lua
fix links detection and improve spam word matching
> fix raid module

- module_message.lua
> Add addalias and editreply commands

- module_logs.lua
- nicknames are displayed incorrectly when they contain underscores
- a condition check if data.nicknames[member.id] is nil to determine if a nickname is known, but later data.nicknames[member.id] is initialized with member.nickname, which can be nil
- the function argument is incorrectly named
> update: improve nicknames logging function and fix some issues

- module_pin.lua
fix: members can pin any message from any channel when the command is executed in its thread.
> fix bug in module pin

- module_warn.lua
> fix: badly named constant

- localization/en.lua
- localization/fr.lua
- module_voice.lua
This PR allows the module to handle certain situations like a bot reboot or an unexpected crash.
I also added support for translations.
> update: module voice

- module_raid.lua
- add spam words
- tweak the algo to allow match token containing space
> update: module raid
